# Generated by Django 4.0.4 on 2022-04-17 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0004_alter_faq_answer_alter_faq_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='last_modi_writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modi_writer_question', to=settings.AUTH_USER_MODEL, verbose_name='최종 수정자'),
        ),
    ]
