# Generated by Django 4.0.3 on 2022-05-09 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_list', models.CharField(choices=[('ER', '문의 등록'), ('CA', '접수 완료'), ('AC', '답변 완료')], default='ER', max_length=10, verbose_name='상태')),
                ('category_list', models.CharField(choices=[('NU', '선택해주세요.'), ('GE', '일반'), ('AC', '계정'), ('ET', '기타')], default='NU', max_length=10, verbose_name='카테고리')),
                ('question', models.CharField(max_length=50, verbose_name='제목')),
                ('user_email', models.EmailField(max_length=128, null=True, verbose_name='이메일')),
                ('email_checkbox', models.BooleanField(default=False, verbose_name='답변수신을 이메일로 받겠습니다.')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='문자메시지')),
                ('phone_checkbox', models.BooleanField(default=False, verbose_name='답변수신을 문자로 받겠습니다.')),
                ('inquiry_content', models.TextField(default='질문 내용을 입력하세요..', verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.TextField(verbose_name='답변내용')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='최종 수정일')),
                ('last_modi_writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modi_writer_question', to=settings.AUTH_USER_MODEL, verbose_name='최종 수정자')),
                ('wh_inquiry', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='support.inquiry')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
        ),
    ]
