# Generated by Django 4.0.4 on 2022-04-16 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='post',
        ),
        migrations.AddField(
            model_name='answer',
            name='wh_inquiry',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='support.inquiry'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
    ]
