# Generated by Django 4.0.3 on 2022-05-09 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='생성일시'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='writer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_writer', to=settings.AUTH_USER_MODEL),
        ),
    ]
