# Generated by Django 4.0.4 on 2022-04-17 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_remove_answer_post_answer_wh_inquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='last_modi_writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modi_writer_question', to=settings.AUTH_USER_MODEL, verbose_name='최종 수정자'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='category_list',
            field=models.CharField(choices=[('NU', '선택해주세요.'), ('GE', '일반'), ('AC', '계정'), ('ET', '기타')], default='NU', max_length=10, verbose_name='카테고리'),
        ),
    ]
