# Generated by Django 4.0.4 on 2022-04-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_remove_inquiry_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='user_email',
            field=models.EmailField(max_length=128, null=True, verbose_name='이메일'),
        ),
    ]
