# Generated by Django 4.0.4 on 2022-04-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_inquiry_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='user_email_cb',
            field=models.BooleanField(default=False, verbose_name='답변수신을 이메일로 받겠습니다.'),
        ),
    ]
