# Generated by Django 4.0.4 on 2022-04-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_inquiry_user_email_cb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='user_email_cb',
            new_name='email_checkbox',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phone_checkbox',
            field=models.BooleanField(default=False, verbose_name='답변수신을 문자로 받겠습니다.'),
        ),
    ]
